Rename workflow and update commit messages

diff --git a/.github/workflows/generate_pihole_cloud.yml b/.github/workflows/generate_pihole_cloud.yml
--- a/.github/workflows/generate_pihole_cloud.yml
+++ b/.github/workflows/generate_pihole_cloud.yml
@@ -1,9 +1,9 @@
-name: Generate Pi-hole Cloudgaming Whitelist
+name: generate_pihole_cloud
 
 on:
   push:
     paths:
-      - 'adguard-allowlist-cloudgaming' # Exakter Dateiname ohne Endung
+      - 'adguard-allowlist-cloudgaming'
   workflow_dispatch:
 
 jobs:
@@ -17,12 +17,10 @@ jobs:
 
       - name: Convert Cloud-Whitelist to Pi-hole
         run: |
-          # Prüft, ob die Datei existiert und wandelt sie für Pi-hole um
           if [ -f "adguard-allowlist-cloudgaming" ]; then
             sed -e 's/@@||//g' -e 's/\^//g' -e 's/\$important//g' -e '/^!/d' -e '/^#/d' -e '/^$/d' "adguard-allowlist-cloudgaming" > pihole-cloudgaming.txt
-            echo "✅ Cloudgaming list converted successfully."
           else
-            echo "❌ File 'adguard-allowlist-cloudgaming' not found!"
+            echo "File not found"
             exit 1
           fi
           
@@ -31,5 +29,5 @@ jobs:
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git add pihole-cloudgaming.txt
-          git commit -m "Update Pi-hole cloudgaming list [auto]" || echo "No changes to commit"
+          git commit -m "Update Pi-hole list" || echo "No changes"
           git push
